# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_data_orang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pengiriman_orang import PengirimanOrang as PO

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 120, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 120, 35, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 310, 100, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 270, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 120, 80, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 30, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 150, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 190, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 150, 120, 20))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 190, 120, 20))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(230, 230, 120, 20))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(230, 270, 120, 20))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 310, 100, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(-10, 0, 721, 531))
        self.label_11.setStyleSheet("background-image: url(:/newPrefix/2920421574.jpg);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_11.raise_()
        self.label_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.label_5.raise_()
        self.lineEdit_2.raise_()
        self.label_7.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton_2.clicked.connect(self.search_data)
        self.pushButton.clicked.connect(self.delete_data)
        self.pushButton_3.clicked.connect(self.openhomepelanggan)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ID"))
        self.pushButton_2.setText(_translate("MainWindow", "Cari"))
        self.pushButton.setText(_translate("MainWindow", "Delete"))
        self.label_5.setText(_translate("MainWindow", "Kategori"))
        self.label_7.setText(_translate("MainWindow", "Delete Data Orang"))
        self.label.setText(_translate("MainWindow", "Nama Pemesanan"))
        self.label_4.setText(_translate("MainWindow", "Alamat Tujuan"))
        self.label_2.setText(_translate("MainWindow", "Alamat Pemesanan"))
        self.pushButton_3.setText(_translate("MainWindow", "Kembali"))
        
    def openhomepelanggan(self):
        import home_pelanggan as hp
        self.window = QtWidgets.QMainWindow()
        self.ui = hp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def search_data(self):
        id = self.lineEdit_2.text()
        if not id:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "ID tidak boleh kosong.")
            return
        result = PO.select_data_by_id(id)
        if result:
            self.label_6.setText(result[0][1])  # Nama Pemesanan
            self.label_8.setText(result[0][2])  # Alamat Pemesanan
            self.label_9.setText(result[0][3])  # Alamat Tujuan
            self.label_10.setText(result[0][4])  # Kategori
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data tidak ditemukan.")

    def delete_data(self):
        id = self.lineEdit_2.text()
        if not id:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "ID tidak boleh kosong.")
            return

        confirm = QtWidgets.QMessageBox.question(
            None, "Konfirmasi", "Apakah Anda yakin ingin menghapus data ini?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )
        if confirm == QtWidgets.QMessageBox.Yes:
            rows_deleted = PO.delete_data(id)
            if rows_deleted > 0:
                QtWidgets.QMessageBox.information(None, "Berhasil", "Data berhasil dihapus.")
                self.label_6.setText("")
                self.label_8.setText("")
                self.label_9.setText("")
                self.label_10.setText("")
            else:
                QtWidgets.QMessageBox.warning(None, "Gagal", "Data gagal dihapus atau tidak ditemukan.")
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
