# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_data_makanan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pengiriman_makanan import PengirimanMakanan as PM

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 240, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 90, 35, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 280, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 120, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 400, 100, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 200, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 90, 80, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 90, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 20, 210, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 120, 120, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 160, 120, 20))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 200, 120, 20))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(220, 240, 120, 20))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(220, 280, 120, 20))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 400, 100, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(-260, 0, 741, 481))
        self.label_13.setStyleSheet("background-image: url(:/newPrefix/533-5338308_food-delivery-png-download-food-delivery-transparent-png.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(90, 320, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(220, 320, 120, 20))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_13.raise_()
        self.label_8.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.label_7.raise_()
        self.lineEdit_2.raise_()
        self.label_3.raise_()
        self.label_10.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.pushButton_3.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Tombol kembali
        self.pushButton_3.clicked.connect(self.openhomepelanggan)

        # Tombol cari untuk pencarian data
        self.pushButton_2.clicked.connect(self.search_data)
        
        # Tombol hapus untuk menghapus data
        self.pushButton.clicked.connect(self.delete_data)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Alamat Penerima"))
        self.label_2.setText(_translate("MainWindow", "Alamat Pengirim"))
        self.pushButton_2.setText(_translate("MainWindow", "Cari"))
        self.label_9.setText(_translate("MainWindow", "Nama Makanan"))
        self.label.setText(_translate("MainWindow", "Nama Pengirim"))
        self.pushButton.setText(_translate("MainWindow", "Hapus"))
        self.label_7.setText(_translate("MainWindow", "Nama Penerima"))
        self.label_3.setText(_translate("MainWindow", "ID"))
        self.label_10.setText(_translate("MainWindow", "Delete Data Makanan"))
        self.pushButton_3.setText(_translate("MainWindow", "Kembali"))
        self.label_14.setText(_translate("MainWindow", "Jumlah Makanan"))
        
    def openhomepelanggan(self):
        import home_pelanggan as hp
        self.window = QtWidgets.QMainWindow()
        self.ui = hp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def search_data(self):
        id = self.lineEdit_2.text()
        if not id:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "ID tidak boleh kosong.")
            return
        result = PM.select_data_by_id(id)
        if result:
            self.label_4.setText(result[0][1])  # Nama Makanan
            self.label_5.setText(result[0][2])    # Nama Pengirim
            self.label_6.setText(result[0][3])  # Nama Penerima
            self.label_11.setText(result[0][4])  # Alamat Pengirim
            self.label_12.setText(result[0][5])  # Alamat Penerima
            self.label_15.setText(str(result[0][6]))  
            
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data tidak ditemukan.")

    def delete_data(self):
        id = self.lineEdit_2.text()
        if not id:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "ID tidak boleh kosong.")
            return

        confirm = QtWidgets.QMessageBox.question(
            None, "Konfirmasi", "Apakah Anda yakin ingin menghapus data ini?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )
        if confirm == QtWidgets.QMessageBox.Yes:
            rows_deleted = PM.delete_data(id)
            if rows_deleted > 0:
                QtWidgets.QMessageBox.information(None, "Berhasil", "Data berhasil dihapus.")
                self.label_4.setText("")
                self.label_5.setText("")
                self.label_6.setText("")
                self.label_11.setText("")
                self.label_12.setText("")
                self.label_15.setText("")
            else:
                QtWidgets.QMessageBox.warning(None, "Gagal", "Data gagal dihapus atau tidak ditemukan.")
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
