# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_pelanggan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from insert_data_barang1 import Ui_MainWindow as InsertDataBarang
from update_data_barang1 import Ui_MainWindow as UpdateDataBarang
from delete_data_barang1 import Ui_MainWindow as DeleteDataBarang
from insert_data_makanan1 import Ui_MainWindow as InsertDataMakanan
from update_data_makanan1 import Ui_MainWindow as UpdateDataMakanan
from delete_data_makanan1 import Ui_MainWindow as DeleteDataMakanan
from insert_data_orang1 import Ui_MainWindow as InsertDataOrang
from update_data_orang1 import Ui_MainWindow as UpdateDataOrang
from delete_data_orang1 import Ui_MainWindow as DeleteDataOrang
from perhitungan_total import hitung_pengiriman_barang,hitung_pengiriman_makanan,hitung_pengiriman_orang, hitung_jarak
from alamat import Alamat
from pengiriman_barang import PengirimanBarang as PB
from pengiriman_makanan import PengirimanMakanan as PM
from pengiriman_orang import PengirimanOrang as PO
from voucher import Voucher
from detail_barang import Ui_MainWindow as DetailBarang
from detail_makanan import Ui_MainWindow as DetailMakanan
from detail_orang import Ui_MainWindow as DetailOrang
 
        

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: rgb(251, 248, 239);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 170, 500))
        self.sidebar.setStyleSheet("QWidget{\n"
"    background-color: rgb(180, 63, 63);\n"
"}\n"
"QPushButton{\n"
"    color:white;\n"
"    text-align:left;\n"
"    height:30px;\n"
"    border:none;\n"
"    padding-left:3px;\n"
"    border-top-left-radius:5px;\n"
"    border-bottom-left-radius:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color : #F5FAFE;\n"
"    color: rgb(180, 63, 63);\n"
"    font-weight:bold;\n"
"    \n"
"}\n"
"Qlabel_2{\n"
"color:white;\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.label = QtWidgets.QLabel(self.sidebar)
        self.label.setGeometry(QtCore.QRect(15, 5, 25, 30))
        self.label.setStyleSheet("QLabel#label {\n"
"color:white;}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-male-user-24 (1).png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.sidebar)
        self.label_2.setGeometry(QtCore.QRect(50, 15, 64, 13))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.JPBarang_2 = QtWidgets.QPushButton(self.sidebar)
        self.JPBarang_2.setGeometry(QtCore.QRect(18, 50, 152, 30))
        self.JPBarang_2.setCheckable(True)
        self.JPBarang_2.setAutoExclusive(True)
        self.JPBarang_2.setObjectName("JPBarang_2")
        self.JPMakanan_2 = QtWidgets.QPushButton(self.sidebar)
        self.JPMakanan_2.setGeometry(QtCore.QRect(18, 90, 152, 30))
        self.JPMakanan_2.setCheckable(True)
        self.JPMakanan_2.setAutoExclusive(True)
        self.JPMakanan_2.setObjectName("JPMakanan_2")
        self.JAOOrang = QtWidgets.QPushButton(self.sidebar)
        self.JAOOrang.setGeometry(QtCore.QRect(18, 130, 152, 30))
        self.JAOOrang.setCheckable(True)
        self.JAOOrang.setAutoExclusive(True)
        self.JAOOrang.setObjectName("JAOOrang")
        self.pembayaran = QtWidgets.QPushButton(self.sidebar)
        self.pembayaran.setGeometry(QtCore.QRect(18, 170, 152, 30))
        self.pembayaran.setCheckable(True)
        self.pembayaran.setAutoExclusive(True)
        self.pembayaran.setObjectName("pembayaran")
        self.Riwayat_2 = QtWidgets.QPushButton(self.sidebar)
        self.Riwayat_2.setGeometry(QtCore.QRect(18, 210, 152, 30))
        self.Riwayat_2.setCheckable(True)
        self.Riwayat_2.setAutoExclusive(True)
        self.Riwayat_2.setObjectName("Riwayat_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_7.setGeometry(QtCore.QRect(42, 470, 75, 23))
        self.pushButton_7.setStyleSheet("QPushButton#pushButton_7{\n"
"    border-radius:5px;\n"
"    \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-log-out-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-log-out-24 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setAutoExclusive(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.content = QtWidgets.QWidget(self.centralwidget)
        self.content.setGeometry(QtCore.QRect(170, 0, 631, 501))
        self.content.setObjectName("content")
        self.header = QtWidgets.QWidget(self.content)
        self.header.setGeometry(QtCore.QRect(0, 0, 631, 40))
        self.header.setObjectName("header")
        self.label_3 = QtWidgets.QLabel(self.header)
        self.label_3.setGeometry(QtCore.QRect(240, 12, 160, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 40, 630, 460))
        self.stackedWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.JPBarang = QtWidgets.QWidget()
        self.JPBarang.setObjectName("JPBarang")
        self.binsertbarang = QtWidgets.QPushButton(self.JPBarang)
        self.binsertbarang.setGeometry(QtCore.QRect(45, 20, 100, 23))
        self.binsertbarang.setObjectName("binsertbarang")
        self.bupdatebarang = QtWidgets.QPushButton(self.JPBarang)
        self.bupdatebarang.setGeometry(QtCore.QRect(190, 20, 100, 23))
        self.bupdatebarang.setObjectName("bupdatebarang")
        self.bdeletebarang = QtWidgets.QPushButton(self.JPBarang)
        self.bdeletebarang.setGeometry(QtCore.QRect(335, 20, 100, 23))
        self.bdeletebarang.setObjectName("bdeletebarang")
        self.viewbarang = QtWidgets.QTableWidget(self.JPBarang)
        self.viewbarang.setGeometry(QtCore.QRect(10, 100, 605, 301))
        self.viewbarang.setObjectName("viewbarang")
        self.viewbarang.setColumnCount(8)
        self.viewbarang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(7, item)
        self.stackedWidget.addWidget(self.JPBarang)
        self.JPMakanan = QtWidgets.QWidget()
        self.JPMakanan.setObjectName("JPMakanan")
        self.binsertmakanan = QtWidgets.QPushButton(self.JPMakanan)
        self.binsertmakanan.setGeometry(QtCore.QRect(35, 20, 110, 23))
        self.binsertmakanan.setObjectName("binsertmakanan")
        self.bupdatemakanan = QtWidgets.QPushButton(self.JPMakanan)
        self.bupdatemakanan.setGeometry(QtCore.QRect(180, 20, 110, 23))
        self.bupdatemakanan.setObjectName("bupdatemakanan")
        self.bdeleteakanan = QtWidgets.QPushButton(self.JPMakanan)
        self.bdeleteakanan.setGeometry(QtCore.QRect(325, 20, 110, 23))
        self.bdeleteakanan.setObjectName("bdeleteakanan")
        self.viewmakanan = QtWidgets.QTableWidget(self.JPMakanan)
        self.viewmakanan.setGeometry(QtCore.QRect(60, 90, 505, 301))
        self.viewmakanan.setObjectName("viewmakanan")
        self.viewmakanan.setColumnCount(7)
        self.viewmakanan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(6, item)
        self.stackedWidget.addWidget(self.JPMakanan)
        self.JAOrang = QtWidgets.QWidget()
        self.JAOrang.setObjectName("JAOrang")
        self.bupdateorang = QtWidgets.QPushButton(self.JAOrang)
        self.bupdateorang.setGeometry(QtCore.QRect(180, 30, 110, 23))
        self.bupdateorang.setObjectName("bupdateorang")
        self.binsertorang = QtWidgets.QPushButton(self.JAOrang)
        self.binsertorang.setGeometry(QtCore.QRect(35, 30, 110, 23))
        self.binsertorang.setObjectName("binsertorang")
        self.bdeleteorang = QtWidgets.QPushButton(self.JAOrang)
        self.bdeleteorang.setGeometry(QtCore.QRect(325, 30, 110, 23))
        self.bdeleteorang.setObjectName("bdeleteorang")
        self.vieworang = QtWidgets.QTableWidget(self.JAOrang)
        self.vieworang.setGeometry(QtCore.QRect(113, 90, 405, 301))
        self.vieworang.setObjectName("vieworang")
        self.vieworang.setColumnCount(5)
        self.vieworang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(4, item)
        self.stackedWidget.addWidget(self.JAOrang)
        self.Pembayaran = QtWidgets.QWidget()
        self.Pembayaran.setObjectName("Pembayaran")
        self.p_barang = QtWidgets.QPushButton(self.Pembayaran)
        self.p_barang.setGeometry(QtCore.QRect(30, 20, 80, 23))
        self.p_barang.setObjectName("p_barang")
        self.p_makanan = QtWidgets.QPushButton(self.Pembayaran)
        self.p_makanan.setGeometry(QtCore.QRect(140, 20, 80, 23))
        self.p_makanan.setObjectName("p_makanan")
        self.p_orang = QtWidgets.QPushButton(self.Pembayaran)
        self.p_orang.setGeometry(QtCore.QRect(250, 20, 80, 23))
        self.p_orang.setObjectName("p_orang")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.Pembayaran)
        self.stackedWidget_2.setGeometry(QtCore.QRect(30, 60, 600, 350))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.barang = QtWidgets.QWidget()
        self.barang.setObjectName("barang")
        self.label_4 = QtWidgets.QLabel(self.barang)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 230, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.barang)
        self.lineEdit.setGeometry(QtCore.QRect(150, 70, 120, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.p_barang_2 = QtWidgets.QPushButton(self.barang)
        self.p_barang_2.setGeometry(QtCore.QRect(300, 70, 30, 20))
        self.p_barang_2.setObjectName("p_barang_2")
        self.label_5 = QtWidgets.QLabel(self.barang)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 20, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.barang)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 80, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.barang)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 80, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.barang)
        self.label_8.setGeometry(QtCore.QRect(300, 110, 80, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.barang)
        self.label_9.setGeometry(QtCore.QRect(30, 170, 80, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.barang)
        self.label_10.setGeometry(QtCore.QRect(300, 170, 80, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.barang)
        self.label_11.setGeometry(QtCore.QRect(150, 110, 120, 20))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.barang)
        self.label_12.setGeometry(QtCore.QRect(150, 140, 120, 20))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.barang)
        self.label_13.setGeometry(QtCore.QRect(420, 110, 120, 20))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.barang)
        self.label_14.setGeometry(QtCore.QRect(150, 170, 120, 20))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.barang)
        self.label_15.setGeometry(QtCore.QRect(420, 170, 120, 20))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.barang)
        self.label_16.setGeometry(QtCore.QRect(30, 200, 80, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.barang)
        self.label_17.setGeometry(QtCore.QRect(300, 200, 80, 20))
        self.label_17.setObjectName("label_17")
        self.comboBox = QtWidgets.QComboBox(self.barang)
        self.comboBox.setGeometry(QtCore.QRect(150, 200, 120, 20))
        self.comboBox.setObjectName("comboBox")
        self.label_18 = QtWidgets.QLabel(self.barang)
        self.label_18.setGeometry(QtCore.QRect(420, 200, 120, 20))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.pushButton_20 = QtWidgets.QPushButton(self.barang)
        self.pushButton_20.setGeometry(QtCore.QRect(300, 230, 75, 20))
        self.pushButton_20.setObjectName("pushButton_20")
        self.stackedWidget_2.addWidget(self.barang)
        self.makanan = QtWidgets.QWidget()
        self.makanan.setObjectName("makanan")
        self.p_barang_3 = QtWidgets.QPushButton(self.makanan)
        self.p_barang_3.setGeometry(QtCore.QRect(310, 70, 30, 20))
        self.p_barang_3.setObjectName("p_barang_3")
        self.label_20 = QtWidgets.QLabel(self.makanan)
        self.label_20.setGeometry(QtCore.QRect(30, 110, 80, 20))
        self.label_20.setObjectName("label_20")
        self.comboBox_2 = QtWidgets.QComboBox(self.makanan)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 200, 120, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_21 = QtWidgets.QLabel(self.makanan)
        self.label_21.setGeometry(QtCore.QRect(160, 170, 120, 20))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.makanan)
        self.label_22.setGeometry(QtCore.QRect(30, 200, 80, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.makanan)
        self.label_23.setGeometry(QtCore.QRect(30, 20, 230, 31))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.makanan)
        self.label_24.setGeometry(QtCore.QRect(320, 200, 80, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.makanan)
        self.label_25.setGeometry(QtCore.QRect(30, 140, 80, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.makanan)
        self.label_26.setGeometry(QtCore.QRect(160, 140, 120, 20))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.pushButton_21 = QtWidgets.QPushButton(self.makanan)
        self.pushButton_21.setGeometry(QtCore.QRect(260, 240, 75, 20))
        self.pushButton_21.setObjectName("pushButton_21")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.makanan)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 70, 120, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_28 = QtWidgets.QLabel(self.makanan)
        self.label_28.setGeometry(QtCore.QRect(160, 110, 120, 20))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.makanan)
        self.label_29.setGeometry(QtCore.QRect(160, 170, 120, 20))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.makanan)
        self.label_30.setGeometry(QtCore.QRect(320, 110, 80, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.makanan)
        self.label_31.setGeometry(QtCore.QRect(30, 170, 80, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.makanan)
        self.label_32.setGeometry(QtCore.QRect(30, 70, 20, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.makanan)
        self.label_33.setGeometry(QtCore.QRect(430, 200, 120, 20))
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.stackedWidget_2.addWidget(self.makanan)
        self.orang = QtWidgets.QWidget()
        self.orang.setObjectName("orang")
        self.p_barang_4 = QtWidgets.QPushButton(self.orang)
        self.p_barang_4.setGeometry(QtCore.QRect(300, 80, 30, 20))
        self.p_barang_4.setObjectName("p_barang_4")
        self.label_35 = QtWidgets.QLabel(self.orang)
        self.label_35.setGeometry(QtCore.QRect(30, 120, 80, 20))
        self.label_35.setObjectName("label_35")
        self.comboBox_3 = QtWidgets.QComboBox(self.orang)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 240, 120, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_38 = QtWidgets.QLabel(self.orang)
        self.label_38.setGeometry(QtCore.QRect(30, 30, 230, 31))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.orang)
        self.label_39.setGeometry(QtCore.QRect(30, 240, 80, 20))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.orang)
        self.label_40.setGeometry(QtCore.QRect(30, 150, 80, 20))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.orang)
        self.label_41.setGeometry(QtCore.QRect(150, 150, 120, 20))
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.pushButton_22 = QtWidgets.QPushButton(self.orang)
        self.pushButton_22.setGeometry(QtCore.QRect(300, 280, 75, 20))
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.orang)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 80, 120, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_43 = QtWidgets.QLabel(self.orang)
        self.label_43.setGeometry(QtCore.QRect(150, 120, 120, 20))
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.orang)
        self.label_44.setGeometry(QtCore.QRect(150, 180, 120, 20))
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.orang)
        self.label_45.setGeometry(QtCore.QRect(30, 180, 80, 20))
        self.label_45.setObjectName("label_45")
        self.label_47 = QtWidgets.QLabel(self.orang)
        self.label_47.setGeometry(QtCore.QRect(30, 80, 20, 20))
        self.label_47.setObjectName("label_47")
        self.label_46 = QtWidgets.QLabel(self.orang)
        self.label_46.setGeometry(QtCore.QRect(30, 210, 80, 20))
        self.label_46.setObjectName("label_46")
        self.label_kategori = QtWidgets.QLabel(self.orang)
        self.label_kategori.setGeometry(QtCore.QRect(150, 210, 120, 20))
        self.label_kategori.setObjectName("L kategori orang")
        self.stackedWidget_2.addWidget(self.orang)
        self.stackedWidget.addWidget(self.Pembayaran)
        self.Riwayat = QtWidgets.QWidget()
        self.Riwayat.setObjectName("Riwayat")
        self.p_barang_5 = QtWidgets.QPushButton(self.Riwayat)
        self.p_barang_5.setGeometry(QtCore.QRect(30, 20, 80, 23))
        self.p_barang_5.setObjectName("p_barang_5")
        self.p_makanan_2 = QtWidgets.QPushButton(self.Riwayat)
        self.p_makanan_2.setGeometry(QtCore.QRect(140, 20, 80, 23))
        self.p_makanan_2.setObjectName("p_makanan_2")
        self.p_orang_2 = QtWidgets.QPushButton(self.Riwayat)
        self.p_orang_2.setGeometry(QtCore.QRect(250, 20, 80, 23))
        self.p_orang_2.setObjectName("p_orang_2")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.Riwayat)
        self.stackedWidget_3.setGeometry(QtCore.QRect(30, 60, 600, 350))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.barang_2 = QtWidgets.QWidget()
        self.barang_2.setObjectName("barang_2")
        self.label_19 = QtWidgets.QLabel(self.barang_2)
        self.label_19.setGeometry(QtCore.QRect(30, 20, 230, 31))
        self.label_19.setObjectName("label_19")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.barang_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 70, 120, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.p_barang_6 = QtWidgets.QPushButton(self.barang_2)
        self.p_barang_6.setGeometry(QtCore.QRect(300, 70, 30, 20))
        self.p_barang_6.setObjectName("p_barang_6")
        self.label_27 = QtWidgets.QLabel(self.barang_2)
        self.label_27.setGeometry(QtCore.QRect(30, 70, 20, 20))
        self.label_27.setObjectName("label_27")
        self.bdetailbarang = QtWidgets.QPushButton(self.barang_2)
        self.bdetailbarang.setGeometry(QtCore.QRect(30, 110, 80, 20))
        self.bdetailbarang.setObjectName("bdetailbarang")
        self.stackedWidget_3.addWidget(self.barang_2)
        self.makanan_2 = QtWidgets.QWidget()
        self.makanan_2.setObjectName("makanan_2")
        self.p_barang_7 = QtWidgets.QPushButton(self.makanan_2)
        self.p_barang_7.setGeometry(QtCore.QRect(310, 70, 30, 20))
        self.p_barang_7.setObjectName("p_barang_7")
        self.label_60 = QtWidgets.QLabel(self.makanan_2)
        self.label_60.setGeometry(QtCore.QRect(30, 20, 230, 31))
        self.label_60.setObjectName("label_60")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.makanan_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 70, 120, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_68 = QtWidgets.QLabel(self.makanan_2)
        self.label_68.setGeometry(QtCore.QRect(30, 70, 20, 20))
        self.label_68.setObjectName("label_68")
        self.bdetailmakanan = QtWidgets.QPushButton(self.makanan_2)
        self.bdetailmakanan.setGeometry(QtCore.QRect(30, 110, 80, 20))
        self.bdetailmakanan.setObjectName("bdetailmakanan")
        self.stackedWidget_3.addWidget(self.makanan_2)
        self.orang_2 = QtWidgets.QWidget()
        self.orang_2.setObjectName("orang_2")
        self.p_barang_8 = QtWidgets.QPushButton(self.orang_2)
        self.p_barang_8.setGeometry(QtCore.QRect(300, 80, 30, 20))
        self.p_barang_8.setObjectName("p_barang_8")
        self.label_71 = QtWidgets.QLabel(self.orang_2)
        self.label_71.setGeometry(QtCore.QRect(30, 30, 250, 31))
        self.label_71.setObjectName("label_71")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.orang_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 80, 120, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_78 = QtWidgets.QLabel(self.orang_2)
        self.label_78.setGeometry(QtCore.QRect(30, 80, 20, 20))
        self.label_78.setObjectName("label_78")
        self.bdetailorang = QtWidgets.QPushButton(self.orang_2)
        self.bdetailorang.setGeometry(QtCore.QRect(30, 120, 80, 20))
        self.bdetailorang.setObjectName("bdetailorang")
        self.stackedWidget_3.addWidget(self.orang_2)
        self.stackedWidget.addWidget(self.Riwayat)
        self.label_jumlah_barang = QtWidgets.QLabel(self.barang)
        self.label_jumlah_barang.setGeometry(QtCore.QRect(30, 230, 100, 20))
        self.label_jumlah_barang.setObjectName("label_jumlah_barang")
        self.input_jumlah_barang = QtWidgets.QLabel(self.barang)
        self.input_jumlah_barang.setGeometry(QtCore.QRect(150, 230, 120, 20))
        self.input_jumlah_barang.setObjectName("input_jumlah_barang")
        self.label_jumlah_makanan = QtWidgets.QLabel(self.makanan)
        self.label_jumlah_makanan.setGeometry(QtCore.QRect(320, 170, 100, 20))
        self.label_jumlah_makanan.setObjectName("label_jumlah_makanan")
        self.input_jumlah_makanan = QtWidgets.QLabel(self.makanan)
        self.input_jumlah_makanan.setGeometry(QtCore.QRect(430, 170, 120, 20))
        self.input_jumlah_makanan.setObjectName("input_jumlah_makanan")
        self.label_alamat_tujuanmakanan = QtWidgets.QLabel(self.makanan)
        self.label_alamat_tujuanmakanan.setGeometry(QtCore.QRect(320, 140, 80, 20))
        self.label_alamat_tujuanmakanan.setObjectName("label_alamat_tujuanmakanan")
        self.input_alamat_tujuanmakanan = QtWidgets.QLabel(self.makanan)
        self.input_alamat_tujuanmakanan.setGeometry(QtCore.QRect(430, 140, 120, 20))
        self.input_alamat_tujuanmakanan.setObjectName("input_alamat_tujuanmakanan")
        self.label_total_harga = QtWidgets.QLabel(self.orang)
        self.label_total_harga.setGeometry(QtCore.QRect(30, 280, 100, 20))
        self.label_total_harga.setObjectName("label_total_harga")
        self.input_total_harga = QtWidgets.QLabel(self.orang)
        self.input_total_harga.setGeometry(QtCore.QRect(150, 280, 120, 20))
        self.input_total_harga.setObjectName("input_total_harga")
        self.label_alamat_tujuanbarang = QtWidgets.QLabel(self.barang)
        self.label_alamat_tujuanbarang.setGeometry(QtCore.QRect(300, 140, 80, 20))
        self.label_alamat_tujuanbarang.setObjectName("label_alamat_tujuanbarang")
        self.input_alamat_tujuanbarang = QtWidgets.QLabel(self.barang)
        self.input_alamat_tujuanbarang.setGeometry(QtCore.QRect(420, 140, 80, 20))
        self.input_alamat_tujuanbarang.setObjectName("input_alamat_tujuanbarang")
        self.input_nama_penerima_makanan = QtWidgets.QLabel(self.makanan)
        self.input_nama_penerima_makanan.setGeometry(QtCore.QRect(430, 110, 120, 20))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.handle_sidebar_clicks()
        #load data ke table barang
        self.load_data_to_table_barang()
        self.load_data_to_table_makanan()
        self.load_data_to_table_orang()
        #handle tombol di jasa pengiriman barang
        self.handle_button_clicks_jasa_pengiriman_barang()
        #handle tombol di jasa pengiriman makanan
        self.handle_button_clicks_jasa_pengiriman_makanan()
        
        self.handle_button_clicks_jasa_antar_orang()
        
        self.pushButton_7.clicked.connect(self.confirm_logout)
        

    def retranslateUi(self, MainWindow):
        
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Pelanggan"))
        self.JPBarang_2.setText(_translate("MainWindow", "Jasa Pengiriman Barang"))
        self.JPMakanan_2.setText(_translate("MainWindow", "Jasa Pengiriman Makanan"))
        self.JAOOrang.setText(_translate("MainWindow", "Jasa Antar Orang"))
        self.pembayaran.setText(_translate("MainWindow", "Pembayaran"))
        self.Riwayat_2.setText(_translate("MainWindow", "Riwayat"))
        self.pushButton_7.setText(_translate("MainWindow", "Log Out"))
        self.label_3.setText(_translate("MainWindow", "Dashboard Pelanggan"))
        self.binsertbarang.setText(_translate("MainWindow", "Insert Data Barang"))
        self.bupdatebarang.setText(_translate("MainWindow", "Update Data Barang"))
        self.bdeletebarang.setText(_translate("MainWindow", "Delete Data Barang"))
        
        item = self.viewbarang.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.viewbarang.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pengirim"))
        item = self.viewbarang.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alamat Pengirim"))
        item = self.viewbarang.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nama Penerima"))
        item = self.viewbarang.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Alamat Penerima"))
        item = self.viewbarang.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Nama Barang"))
        item = self.viewbarang.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Berat Barang"))
        item = self.viewbarang.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Jumlah Barang"))
        self.binsertmakanan.setText(_translate("MainWindow", "Insert Data Makanan"))
        self.bupdatemakanan.setText(_translate("MainWindow", "Update Data Makanan"))
        self.bdeleteakanan.setText(_translate("MainWindow", "Delete Data Makanan"))
        
        item = self.viewmakanan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.viewmakanan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pengirim"))
        item = self.viewmakanan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alamat Pengirim"))
        item = self.viewmakanan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nama Penerima"))
        item = self.viewmakanan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Alamat Penerima"))
        item = self.viewmakanan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Nama Makanan"))
        item = self.viewmakanan.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Jumlah Makanan"))
        self.bupdateorang.setText(_translate("MainWindow", "Update Data Orang"))
        self.binsertorang.setText(_translate("MainWindow", "Insert Data Orang "))
        self.bdeleteorang.setText(_translate("MainWindow", "Delete Data Orang"))
        item = self.vieworang.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.vieworang.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pemesan"))
        item = self.vieworang.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alamat Pemesan"))
        item = self.vieworang.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Alamat Tujuan"))
        item = self.vieworang.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Kategori"))
        self.p_barang.setText(_translate("MainWindow", "Barang"))
        self.p_makanan.setText(_translate("MainWindow", "Makanan"))
        self.p_orang.setText(_translate("MainWindow", "Orang"))
        self.label_4.setText(_translate("MainWindow", "Input id pengiriman barang yang ingin dibayar"))
        self.p_barang_2.setText(_translate("MainWindow", "cari"))
        self.label_5.setText(_translate("MainWindow", "ID"))
        self.label_6.setText(_translate("MainWindow", "Nama Pengirim"))
        self.label_7.setText(_translate("MainWindow", "Alamat Pengirim"))
        self.label_8.setText(_translate("MainWindow", "Nama Penerima"))
        self.label_alamat_tujuanbarang.setText(_translate("MainWindow", "Alamat Penerima"))
        self.label_9.setText(_translate("MainWindow", "Nama Barang"))
        self.label_10.setText(_translate("MainWindow", "Berat Barang"))
        self.label_jumlah_barang.setText(_translate("MainWindow", "Jumlah Barang"))
        self.label_16.setText(_translate("MainWindow", "Voucher"))
        self.label_17.setText(_translate("MainWindow", "Total Harga"))
        self.pushButton_20.setText(_translate("MainWindow", "Bayar"))
        self.p_barang_3.setText(_translate("MainWindow", "cari"))
        self.label_20.setText(_translate("MainWindow", "Nama Pengirim"))
        self.label_22.setText(_translate("MainWindow", "Voucher"))
        self.label_23.setText(_translate("MainWindow", "Input id pengiriman makanan yang ingin dibayar"))
        self.label_24.setText(_translate("MainWindow", "Total Harga"))
        self.label_25.setText(_translate("MainWindow", "Alamat Pengirim"))
        self.pushButton_21.setText(_translate("MainWindow", "Bayar"))
        self.label_30.setText(_translate("MainWindow", "Nama Penerima"))
        self.label_31.setText(_translate("MainWindow", "Nama Makanan"))
        self.label_alamat_tujuanmakanan.setText(_translate("MainWindow", "Alamat Penerima"))
        self.label_jumlah_makanan.setText(_translate("MainWindow", "Jumlah Makanan"))
        self.label_32.setText(_translate("MainWindow", "ID"))
        self.p_barang_4.setText(_translate("MainWindow", "cari"))
        self.label_35.setText(_translate("MainWindow", "Nama Pemesan"))
        self.label_38.setText(_translate("MainWindow", "Input id pengantaran orang yang ingin dibayar"))
        self.label_39.setText(_translate("MainWindow", "Voucher"))
        self.label_40.setText(_translate("MainWindow", "Alamat Pemesan"))
        self.label_total_harga.setText(_translate("MainWindow", "Total Harga"))
        self.pushButton_22.setText(_translate("MainWindow", "Bayar"))
        self.label_45.setText(_translate("MainWindow", "Alamat Tujuan"))
        self.label_47.setText(_translate("MainWindow", "ID"))
        self.label_46.setText(_translate("MainWindow", "Kategori"))
        self.p_barang_5.setText(_translate("MainWindow", "Barang"))
        self.p_makanan_2.setText(_translate("MainWindow", "Makanan"))
        self.p_orang_2.setText(_translate("MainWindow", "Orang"))
        self.label_19.setText(_translate("MainWindow", "Input id pengiriman barang untuk lihat riwayat"))
        self.p_barang_6.setText(_translate("MainWindow", "cari"))
        self.label_27.setText(_translate("MainWindow", "ID"))
        self.bdetailbarang.setText(_translate("MainWindow", "Detail"))
        self.p_barang_7.setText(_translate("MainWindow", "cari"))
        self.label_60.setText(_translate("MainWindow", "Input id pengiriman makanan untuk lihat riwayat"))
        self.label_68.setText(_translate("MainWindow", "ID"))
        self.bdetailmakanan.setText(_translate("MainWindow", "Detail"))
        self.p_barang_8.setText(_translate("MainWindow", "cari"))
        self.label_71.setText(_translate("MainWindow", "Input id pengantaran orang untuk melihat riwayat"))
        self.label_78.setText(_translate("MainWindow", "ID"))
        self.bdetailorang.setText(_translate("MainWindow", "Detail"))
        
    def handle_sidebar_clicks(self):
        self.JPBarang_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.JPBarang))
        self.JPMakanan_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.JPMakanan))
        self.JAOOrang.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.JAOrang))
        self.pembayaran.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Pembayaran))
        self.Riwayat_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Riwayat))
        # Set koneksi tombol di menu Pembayaran
        self.p_barang.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.barang))
        self.p_makanan.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.makanan))
        self.p_orang.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.orang))
        #set koneksi di halaman pembayaran barang
        self.p_barang_2.clicked.connect(self.cari_data_pembayaran_barang)
        # Panggil fungsi load voucher ke combobox saat halaman pembayaran barang diakses
        self.p_barang_2.clicked.connect(lambda: self.load_voucher_to_combobox_barang())
        self.comboBox.currentIndexChanged.connect(self.on_voucher_selected_barang)
        self.pushButton_20.clicked.connect(self.handle_bayar_barang)
        
        #set koneksi di halaman pembayaran makanan
        self.p_barang_3.clicked.connect(self.cari_data_pembayaran_makanan)
        self.p_barang_3.clicked.connect(lambda: self.load_voucher_to_combobox_makanan())
        self.comboBox_2.currentIndexChanged.connect(self.on_voucher_selected_makanan)
        self.pushButton_21.clicked.connect(self.handle_bayar_makanan)
        
        #set koneksi di halaman pembayaran orang
        self.p_barang_4.clicked.connect(self.cari_data_pembayaran_orang)
        self.p_barang_4.clicked.connect(lambda: self.load_voucher_to_combobox_orang())
        self.comboBox_3.currentIndexChanged.connect(self.on_voucher_selected_orang)
        self.pushButton_22.clicked.connect(self.handle_bayar_orang)
        
        
        # Set default halaman di Pembayaran
        self.stackedWidget_2.setCurrentWidget(self.barang)
        # Set koneksi tombol di menu Riwayat
        self.p_barang_5.clicked.connect(lambda: self.stackedWidget_3.setCurrentWidget(self.barang_2))
        self.p_makanan_2.clicked.connect(lambda: self.stackedWidget_3.setCurrentWidget(self.makanan_2))
        self.p_orang_2.clicked.connect(lambda: self.stackedWidget_3.setCurrentWidget(self.orang_2))
        
        # Set default halaman di Riwayat
        self.stackedWidget_3.setCurrentWidget(self.barang_2)
        
        #button riwayat barang
        self.p_barang_6.clicked.connect(self.cari_riwayat_barang)
        self.bdetailbarang.clicked.connect(self.buka_detail_barang)
        
        #button riwayat makanan
        self.p_barang_7.clicked.connect(self.cari_riwayat_makanan)
        self.bdetailmakanan.clicked.connect(self.buka_detail_makanan)
        
        #button riwayat orang
        self.p_barang_8.clicked.connect(self.cari_riwayat_orang)
        self.bdetailorang.clicked.connect(self.buka_detail_orang)

        self.detail_data_barang = None 
        self.detail_data_makanan = None
        self.detail_data_orang = None

        
        #fungsi untuk tombol crud jasa pengiriman barang
    def handle_button_clicks_jasa_pengiriman_barang(self):
        self.binsertbarang.clicked.connect(self.openinsertDataBarang)
        self.bupdatebarang.clicked.connect(self.openupdateDataBarang)
        self.bdeletebarang.clicked.connect(self.opendeleteDataBarang)
    
        #fungsi untuk tombol crud jasa pengiriman makanan
    def handle_button_clicks_jasa_pengiriman_makanan(self):
        self.binsertmakanan.clicked.connect(self.openinsertDataMakanan)
        self.bupdatemakanan.clicked.connect(self.openupdateDataMakanan)
        self.bdeleteakanan.clicked.connect(self.opendeleteDataMakanan)
        #fungsi untuk tombol crud jasa pengiriman orang
    def handle_button_clicks_jasa_antar_orang(self):
        self.binsertorang.clicked.connect(self.openinsertDataOrang)
        self.bupdateorang.clicked.connect(self.openupdateDataOrang)
        self.bdeleteorang.clicked.connect(self.opendeleteDataOrang)
    def openinsertDataBarang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = InsertDataBarang()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def openupdateDataBarang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = UpdateDataBarang()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def opendeleteDataBarang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = DeleteDataBarang()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    


# fungsi untuk tombol crud data makananan
    def openinsertDataMakanan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = InsertDataMakanan()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def openupdateDataMakanan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = UpdateDataMakanan()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def opendeleteDataMakanan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = DeleteDataMakanan()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

# fungsi untuk tombol crud data orang
    def openinsertDataOrang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = InsertDataOrang()
        self.ui.setupUi(self.window)
        self.window.show()        
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def openupdateDataOrang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = UpdateDataOrang()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def opendeleteDataOrang(self):
        self.window = QtWidgets.QMainWindow()        
        self.ui = DeleteDataOrang()
        self.ui.setupUi(self.window)
        self.window.show()        
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
        
        
    def load_data_to_table_barang(self):
        self.viewbarang.setRowCount(0)
        data = PB.load_all_data()
        for row_number, row_data in enumerate(data):
            self.viewbarang.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.viewbarang.setItem(row_number, column_number, item)
                 
    def load_data_to_table_makanan(self):
        self.viewmakanan.setRowCount(0)
        data = PM.load_all_data()
        for row_number, row_data in enumerate(data):
            self.viewmakanan.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.viewmakanan.setItem(row_number, column_number, item)
    def load_data_to_table_orang(self):
        self.vieworang.setRowCount(0)
        data = PO.load_all_data()
        for row_number, row_data in enumerate(data):
            self.vieworang.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.vieworang.setItem(row_number, column_number, item)
                
    # fungsi untuk pembayaran barang
    def load_voucher_to_combobox_barang(self):
        voucher_list = Voucher.select_data()  
        self.comboBox.clear()  
        self.comboBox.addItem("Pilih Voucher") 
        self.comboBox.addItems(voucher_list)  
    def cari_data_pembayaran_barang(self):
        id = self.lineEdit.text() 
        data = PB.select_data_by_id_pembayaran(id)  
        if data:
            if data[0][10] == "Sudah Dibayar": 
                QtWidgets.QMessageBox.information(
                None, "Informasi", f"ID {id} sudah dibayar!"
            )
                return  
            self.label_11.setText(data[0][1])  
            self.label_12.setText(data[0][2])  
            self.label_13.setText(data[0][3])  
            self.input_alamat_tujuanbarang.setText(data[0][4])
            self.label_14.setText(str(data[0][5]))  
            self.label_15.setText(str(data[0][6])) 
            self.input_jumlah_barang.setText(str(data[0][8])) 
            self.load_voucher_to_combobox_barang()
            self.hitung_total_harga_barang()
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")
    def hitung_total_harga_barang(self):
        id = self.lineEdit.text()  
        data = PB.select_data_by_id_pembayaran(id)
        if data:
            kota_awal = data[0][2]
            kota_tujuan = data[0][4]
            lat1, lon1 = Alamat.get_koordinat_dari_db(kota_awal)
            lat2, lon2 = Alamat.get_koordinat_dari_db(kota_tujuan)
            jarak = hitung_jarak(lat1, lon1, lat2, lon2)
            berat = data[0][6] if data[0][6] else 0
            jumlah = data[0][8] if data[0][8] else 0
            tarif_kg = 5000
            tarif_unit = 2000
            tarif_km = 1000
            # Ambil kode voucher
            kode_voucher = self.comboBox.currentText()
            if kode_voucher == "Pilih Voucher":
                diskon = 0
            else:
                diskon_persen = Voucher.get_diskon_voucher(kode_voucher)
                diskon = (diskon_persen / 100) * (berat * tarif_kg + jumlah * tarif_unit + jarak * tarif_km)
            total_harga = hitung_pengiriman_barang(jarak=jarak,berat=berat,jumlah=jumlah,tarif_kg=tarif_kg,tarif_unit=tarif_unit,tarif_km=tarif_km,diskon=diskon)
            total_harga = round(total_harga)
            total_harga_terformat = f"{total_harga:,}"
            self.label_18.setText(total_harga_terformat)
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")

    def on_voucher_selected_barang(self):
        self.comboBox.currentIndexChanged.disconnect()
        id = self.lineEdit.text()
        if id:
            self.hitung_total_harga_barang() 
        self.comboBox.currentIndexChanged.connect(self.on_voucher_selected_barang)
        
    def handle_bayar_barang(self):
        id = self.lineEdit.text()
        total_harga = self.label_18.text().replace(",", "")  
        kode_voucher = self.comboBox.currentText()
        try:
            rows_updated = PB.bayar_pengiriman_barang(
                id=id,
                harga=total_harga,
                voucher=kode_voucher if kode_voucher != "Tidak Menggunakan Voucher" else None
            )
            if rows_updated > 0:
                QtWidgets.QMessageBox.information(None, "Sukses", "Pembayaran berhasil!")
            else:
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")

        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", f"Terjadi kesalahan: {e}")


    # fungsi untuk pembayaran makanan
    def load_voucher_to_combobox_makanan(self):
        voucher_list = Voucher.select_data()  
        self.comboBox_2.clear()  
        self.comboBox_2.addItem("Pilih Voucher") 
        self.comboBox_2.addItems(voucher_list)
    def cari_data_pembayaran_makanan(self):
        id = self.lineEdit_2.text()  
        data = PM.select_data_by_id_pembayaran(id)  
        if data:
            if data[0][9] == "Sudah Dibayar": 
                QtWidgets.QMessageBox.information(
                None, "Informasi", f"ID {id} sudah dibayar!"
            )
                return  
            self.label_28.setText(data[0][1])  # Nama Pengirim
            self.label_26.setText(data[0][2]) # Alamat Pengirim
            self.input_nama_penerima_makanan.setText(data[0][3])  # Nama Penerima
            self.input_alamat_tujuanmakanan.setText(data[0][4])  
            self.label_29.setText(data[0][5]) # Nama Makanan
            self.input_jumlah_makanan.setText(str(data[0][8]))  # Jumlah Makanan
            self.load_voucher_to_combobox_makanan()
            self.hitung_total_harga_makanan()
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")
    
    def hitung_total_harga_makanan(self):
        id = self.lineEdit_2.text()  
        data = PM.select_data_by_id_pembayaran(id)
        if data:
            kota_awal = data[0][2]  
            kota_tujuan = data[0][4] 
            lat1, lon1 = Alamat.get_koordinat_dari_db(kota_awal)
            lat2, lon2 = Alamat.get_koordinat_dari_db(kota_tujuan)
            jarak = hitung_jarak(lat1, lon1, lat2, lon2)

            jumlah_makanan = data[0][8]  
            tarif_km = 500  
            tarif_per_makanan = 2000   
            kode_voucher = self.comboBox_2.currentText()
            if kode_voucher == "Pilih Voucher":
                diskon = 0
            else:
                diskon_persen = Voucher.get_diskon_voucher(kode_voucher)
                diskon = (diskon_persen / 100) * (jumlah_makanan * tarif_per_makanan + (jarak * tarif_km))
            # Hitung total harga
            total_harga = hitung_pengiriman_makanan(jarak=jarak,jumlah=jumlah_makanan,tarif_per_makanan=tarif_per_makanan,tarif_km=tarif_km,diskon=diskon)
            total_harga = round(total_harga)
            self.label_33.setText(f"{total_harga:,}") 
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")
    def on_voucher_selected_makanan(self):
        self.comboBox_2.currentIndexChanged.disconnect()
        id = self.lineEdit_2.text()
        if id:
            self.hitung_total_harga_makanan() 
        self.comboBox_2.currentIndexChanged.connect(self.on_voucher_selected_makanan)

    def handle_bayar_makanan(self):
        id = self.lineEdit_2.text() 
        total_harga = self.label_33.text().replace(",", "")  
        kode_voucher = self.comboBox_2.currentText()
        try:
            rows_updated = PM.bayar_pengiriman_makanan(
                id=id,
                harga=total_harga,
                voucher=kode_voucher if kode_voucher != "Tidak Menggunakan Voucher" else None
            )
            if rows_updated > 0:
                QtWidgets.QMessageBox.information(None, "Sukses", "Pembayaran berhasil!")
            else:
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")

        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", f"Terjadi kesalahan: {e}")
            
    def load_voucher_to_combobox_orang(self):
        voucher_list = Voucher.select_data()  
        self.comboBox_3.clear()  
        self.comboBox_3.addItem("Pilih Voucher") 
        self.comboBox_3.addItems(voucher_list)
    def cari_data_pembayaran_orang(self):
        id = self.lineEdit_3.text()  
        data = PO.select_data_by_id_pembayaran(id)  
        if data:
            if data[0][7] == "Sudah Dibayar": 
                QtWidgets.QMessageBox.information(
                None, "Informasi", f"ID {id} sudah dibayar!"
            )
                return  
            self.label_43.setText(data[0][1]) 
            self.label_41.setText(data[0][2])  
            self.label_44.setText(data[0][3]) 
            self.label_kategori.setText(data[0][4])  
            self.load_voucher_to_combobox_orang()
            self.hitung_total_harga_orang()
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")
    def hitung_total_harga_orang(self):
        id = self.lineEdit_3.text()  
        data = PO.select_data_by_id_pembayaran(id)  
        if data:
            kota_awal = data[0][2]  
            kota_tujuan = data[0][3]  
            lat1, lon1 = Alamat.get_koordinat_dari_db(kota_awal)
            lat2, lon2 = Alamat.get_koordinat_dari_db(kota_tujuan)
            jarak = hitung_jarak(lat1, lon1, lat2, lon2)
            kategori = data[0][4]  

            tarif_bike = 5000 
            tarif_car = 10000  
            tarif_km = 2000    
            kode_voucher = self.comboBox_3.currentText()
            if kode_voucher == "Pilih Voucher":
                diskon = 0
            else:
                diskon_persen = Voucher.get_diskon_voucher(kode_voucher)
                diskon = (diskon_persen / 100) * (jarak * tarif_km + (tarif_bike if kategori == 'bike' else tarif_car))
            total_harga = hitung_pengiriman_orang(jarak, kategori, tarif_bike, tarif_car, tarif_km, diskon)
            total_harga = round(total_harga)
            self.input_total_harga.setText(f"{total_harga:,}")
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")
    def on_voucher_selected_orang(self):
        self.comboBox_3.currentIndexChanged.disconnect()
        id = self.lineEdit_3.text()
        if id:
            self.hitung_total_harga_orang() 
        self.comboBox_3.currentIndexChanged.connect(self.on_voucher_selected_orang)
    def handle_bayar_orang(self):
        id = self.lineEdit_3.text()  
        harga = self.input_total_harga.text().replace(",", "")  
        voucher = self.comboBox_3.currentText()  
        try:
            rows_updated = PO.bayar_pengiriman_orang(id=id, harga=harga, voucher=voucher)
            if rows_updated > 0:
                QtWidgets.QMessageBox.information(None, "Sukses", "Pembayaran berhasil!")
            else:
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!")
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", f"Terjadi kesalahan: {e}")

    def cari_riwayat_barang(self):
        id = self.lineEdit_4.text()
        if not id:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Masukkan ID!")
            return

        data = PB.detail_pengiriman_barang(id)
        if data:
            if data[13] == "Sudah Dibayar": 
                QtWidgets.QMessageBox.information(None, "Info", "Data ditemukan!")
                self.detail_data_barang = data 
            else:
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Data belum dibayar!")
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data tidak ditemukan!")
    
    def buka_detail_barang(self):
        if not self.detail_data_barang:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Tidak ada data untuk ditampilkan!")
            return

        self.detail_window = QtWidgets.QMainWindow()
        self.ui = DetailBarang()  # Pastikan kelas ini adalah kelas untuk window detail
        self.ui.setupUi(self.detail_window)

        # Isi data ke jendela detail
        self.ui.label_15.setText(self.detail_data_barang[1])  # Nama Pengirim
        self.ui.label_16.setText(self.detail_data_barang[2])  # Alamat Pengirim
        self.ui.label_17.setText(self.detail_data_barang[3])  # Nama Penerima
        self.ui.label_18.setText(self.detail_data_barang[4])  # Alamat Penerima
        self.ui.label_19.setText(self.detail_data_barang[5])  # Nama Barang
        self.ui.label_20.setText(str(self.detail_data_barang[6]))  # Berat Barang
        self.ui.label_21.setText(str(self.detail_data_barang[7]))  # Jumlah Barang
        self.ui.label_22.setText(self.detail_data_barang[8])  # Tanggal Pengiriman
        self.ui.label_23.setText(self.detail_data_barang[9])  # Tanggal Penerimaan
        self.ui.label_24.setText(self.detail_data_barang[10])  # Status
        self.ui.label_25.setText(f"Rp {self.detail_data_barang[11]:,.2f}")  # Total Harga
        self.ui.label_26.setText(self.detail_data_barang[12] if self.detail_data_barang[12] else "Tidak Ada")  # Voucher
        self.ui.label_27.setText(self.detail_data_barang[13])  # Status Pembayaran
        # Tambahkan data lainnya sesuai indeks kolom

        self.detail_window.show()
    
    def cari_riwayat_makanan(self):
        id = self.lineEdit_5.text()
        if not id:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Masukkan ID!")
            return

        data = PM.detail_pengiriman_makanan(id)
        if data:
            if data[12] == "Sudah Dibayar": 
                QtWidgets.QMessageBox.information(None, "Info", "Data ditemukan!")
                self.detail_data_makanan = data 
            else:
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Data belum dibayar!")
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data tidak ditemukan!")
    
    def buka_detail_makanan(self):
        if not self.detail_data_makanan:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Tidak ada data untuk ditampilkan!")
            return

        self.detail_window = QtWidgets.QMainWindow()
        self.ui = DetailMakanan()  
        self.ui.setupUi(self.detail_window)
        self.ui.label_15.setText(self.detail_data_makanan[1])  
        self.ui.label_16.setText(self.detail_data_makanan[2])  
        self.ui.label_17.setText(self.detail_data_makanan[3]) 
        self.ui.label_18.setText(self.detail_data_makanan[4])  
        self.ui.label_19.setText(self.detail_data_makanan[5])  
        self.ui.label_21.setText(str(self.detail_data_makanan[6])) 
        self.ui.label_22.setText(self.detail_data_makanan[7])  
        self.ui.label_23.setText(self.detail_data_makanan[8])  
        self.ui.label_24.setText(self.detail_data_makanan[9])  
        self.ui.label_25.setText(f"Rp {self.detail_data_makanan[10]:,.2f}") 
        self.ui.label_26.setText(self.detail_data_makanan[11] if self.detail_data_makanan[11] else "Tidak Ada")  
        self.ui.label_27.setText(self.detail_data_makanan[12])  

        self.detail_window.show()
        
    def cari_riwayat_orang(self):
        id = self.lineEdit_6.text()
        if not id:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Masukkan ID!")
            return

        data = PO.detail_pengiriman_orang(id)
        if data:
            if data[8] == "Sudah Dibayar": 
                QtWidgets.QMessageBox.information(None, "Info", "Data ditemukan!")
                self.detail_data_orang = data 
            else:
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Data belum dibayar!")
        else:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Data tidak ditemukan!")
    
    def buka_detail_orang(self):
        if not self.detail_data_orang:
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Tidak ada data untuk ditampilkan!")
            return

        self.detail_window = QtWidgets.QMainWindow()
        self.ui = DetailOrang() 
        self.ui.setupUi(self.detail_window)
        self.ui.label_15.setText(self.detail_data_orang[1])  
        self.ui.label_16.setText(self.detail_data_orang[2]) 
        self.ui.label_17.setText(self.detail_data_orang[3]) 
        self.ui.label_18.setText(self.detail_data_orang[4])  
        self.ui.label_19.setText(self.detail_data_orang[5])  
        self.ui.label_20.setText(f"Rp {self.detail_data_orang[6]:,.2f}")   
        self.ui.label_21.setText(self.detail_data_orang[7] if self.detail_data_orang[7] else "Tidak Ada")  
        self.ui.label_22.setText(self.detail_data_orang[8])  
        self.detail_window.show()
    
    def confirm_logout(self):
        from welcome import Ui_Form as wel
        reply = QtWidgets.QMessageBox.question(
            None, "Konfirmasi Logout",
            "Apakah Anda yakin ingin logout?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )
        if reply == QtWidgets.QMessageBox.Yes:
            self.window = QtWidgets.QWidget()
            self.ui = wel()
            self.ui.setupUi(self.window)
            self.window.show()
            QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

import icon_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
