# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from insert_data_tempat import Ui_MainWindow as InsertTempat
from update_data_tempat import Ui_MainWindow as UpdateTempat
from delete_data_tempat import Ui_MainWindow as DeleteTempat
from insert_voucher import Ui_MainWindow as InsertVoucher
from update_voucher import Ui_MainWindow as UpdateVoucher
from delete_voucher import Ui_MainWindow as DeleteVoucher
from pengiriman_barang import PengirimanBarang as PB
from pengiriman_makanan import PengirimanMakanan as PM
from pengiriman_orang import PengirimanOrang as PO
from alamat import Alamat as AL
from voucher import Voucher as VC
from riwayat_barang import Ui_MainWindow as RB
from riwayat_makanan import Ui_MainWindow as RM
from riwayat_orang import Ui_MainWindow as RO 
from update_data_pengiriman_barang import Ui_MainWindow as DetailPengirimanBarang
from update_data_pengiriman_makanan import Ui_MainWindow as DetailPengirimanMakanan
from update_data_pengiriman_orang import Ui_MainWindow as DetailAntarOrang

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.content = QtWidgets.QWidget(self.centralwidget)
        self.content.setGeometry(QtCore.QRect(170, 0, 631, 501))
        self.content.setObjectName("content")
        self.header = QtWidgets.QWidget(self.content)
        self.header.setGeometry(QtCore.QRect(0, 0, 631, 40))
        self.header.setObjectName("header")
        self.label_3 = QtWidgets.QLabel(self.header)
        self.label_3.setGeometry(QtCore.QRect(240, 12, 160, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 40, 630, 460))
        self.stackedWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.sw_pb = QtWidgets.QWidget()
        self.sw_pb.setObjectName("sw_pb")
        self.B_updatebarang = QtWidgets.QPushButton(self.sw_pb)
        self.B_updatebarang.setGeometry(QtCore.QRect(440, 420, 180, 23))
        self.B_updatebarang.setObjectName("B_updatebarang")
        self.viewbarang = QtWidgets.QTableWidget(self.sw_pb)
        self.viewbarang.setGeometry(QtCore.QRect(10, 20, 605, 391))
        self.viewbarang.setObjectName("viewbarang")
        self.viewbarang.setColumnCount(14)
        self.viewbarang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewbarang.setHorizontalHeaderItem(13, item)
        self.stackedWidget.addWidget(self.sw_pb)
        self.sw_pm = QtWidgets.QWidget()
        self.sw_pm.setObjectName("sw_pm")
        self.viewmakanan = QtWidgets.QTableWidget(self.sw_pm)
        self.viewmakanan.setGeometry(QtCore.QRect(10, 20, 605, 391))
        self.viewmakanan.setObjectName("viewmakanan")
        self.viewmakanan.setColumnCount(13)
        self.viewmakanan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewmakanan.setHorizontalHeaderItem(12, item)
        self.B_updatemakanan = QtWidgets.QPushButton(self.sw_pm)
        self.B_updatemakanan.setGeometry(QtCore.QRect(440, 430, 180, 23))
        self.B_updatemakanan.setObjectName("B_updatemakanan")
        self.stackedWidget.addWidget(self.sw_pm)
        self.sw_po = QtWidgets.QWidget()
        self.sw_po.setObjectName("sw_po")
        self.vieworang = QtWidgets.QTableWidget(self.sw_po)
        self.vieworang.setGeometry(QtCore.QRect(10, 20, 605, 391))
        self.vieworang.setObjectName("vieworang")
        self.vieworang.setColumnCount(9)
        self.vieworang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.vieworang.setHorizontalHeaderItem(8, item)
        self.B_updateorang = QtWidgets.QPushButton(self.sw_po)
        self.B_updateorang.setGeometry(QtCore.QRect(440, 420, 180, 23))
        self.B_updateorang.setObjectName("B_updateorang")
        self.stackedWidget.addWidget(self.sw_po)
        self.DataTempat = QtWidgets.QWidget()
        self.DataTempat.setObjectName("DataTempat")
        self.binsertTempat = QtWidgets.QPushButton(self.DataTempat)
        self.binsertTempat.setGeometry(QtCore.QRect(75, 20, 110, 23))
        self.binsertTempat.setObjectName("binsertTempat")
        self.bupdateTempat = QtWidgets.QPushButton(self.DataTempat)
        self.bupdateTempat.setGeometry(QtCore.QRect(260, 20, 110, 23))
        self.bupdateTempat.setObjectName("bupdateTempat")
        self.bdeleteTempat = QtWidgets.QPushButton(self.DataTempat)
        self.bdeleteTempat.setGeometry(QtCore.QRect(445, 20, 110, 23))
        self.bdeleteTempat.setObjectName("bdeleteTempat")
        self.viewTempat = QtWidgets.QTableWidget(self.DataTempat)
        self.viewTempat.setGeometry(QtCore.QRect(110, 90, 410, 301))
        self.viewTempat.setObjectName("viewTempat")
        self.viewTempat.setColumnCount(4)
        self.viewTempat.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.viewTempat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewTempat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewTempat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewTempat.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.DataTempat)
        self.DataVoucer = QtWidgets.QWidget()
        self.DataVoucer.setObjectName("DataVoucer")
        self.bupdateVoucer = QtWidgets.QPushButton(self.DataVoucer)
        self.bupdateVoucer.setGeometry(QtCore.QRect(260, 30, 110, 23))
        self.bupdateVoucer.setObjectName("bupdateVoucer")
        self.binsertVoucer = QtWidgets.QPushButton(self.DataVoucer)
        self.binsertVoucer.setGeometry(QtCore.QRect(75, 30, 110, 23))
        self.binsertVoucer.setObjectName("binsertVoucer")
        self.bdeletVoucer = QtWidgets.QPushButton(self.DataVoucer)
        self.bdeletVoucer.setGeometry(QtCore.QRect(445, 30, 110, 23))
        self.bdeletVoucer.setObjectName("bdeletVoucer")
        self.viewvoucher = QtWidgets.QTableWidget(self.DataVoucer)
        self.viewvoucher.setGeometry(QtCore.QRect(160, 90, 310, 301))
        self.viewvoucher.setObjectName("viewvoucher")
        self.viewvoucher.setColumnCount(3)
        self.viewvoucher.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.viewvoucher.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewvoucher.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewvoucher.setHorizontalHeaderItem(2, item)
        self.stackedWidget.addWidget(self.DataVoucer)
        self.Pembayaran = QtWidgets.QWidget()
        self.Pembayaran.setObjectName("Pembayaran")
        self.stackedWidget.addWidget(self.Pembayaran)
        self.Riwayat = QtWidgets.QWidget()
        self.Riwayat.setObjectName("Riwayat")
        self.p_makanan_2 = QtWidgets.QPushButton(self.Riwayat)
        self.p_makanan_2.setGeometry(QtCore.QRect(30, 70, 210, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.p_makanan_2.setFont(font)
        self.p_makanan_2.setObjectName("p_makanan_2")
        self.p_orang_2 = QtWidgets.QPushButton(self.Riwayat)
        self.p_orang_2.setGeometry(QtCore.QRect(30, 120, 210, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.p_orang_2.setFont(font)
        self.p_orang_2.setObjectName("p_orang_2")
        self.p_makanan_3 = QtWidgets.QPushButton(self.Riwayat)
        self.p_makanan_3.setGeometry(QtCore.QRect(30, 20, 210, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.p_makanan_3.setFont(font)
        self.p_makanan_3.setObjectName("p_makanan_3")
        self.stackedWidget.addWidget(self.Riwayat)
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 170, 500))
        self.sidebar.setStyleSheet("QWidget{\n"
"    background-color: rgb(63, 63, 180);\n"
"}\n"
"QPushButton{\n"
"    color: white;\n"
"    text-align: left;\n"
"    height: 30px;\n"
"    border: none;\n"
"    padding-left: 3px;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color: rgb(63, 63, 180);\n"
"    font-weight: bold;\n"
"}\n"
"QLabel_2{\n"
"    color: white;\n"
"}\n"
"")
        self.sidebar.setObjectName("sidebar")
        self.label = QtWidgets.QLabel(self.sidebar)
        self.label.setGeometry(QtCore.QRect(15, 5, 25, 30))
        self.label.setStyleSheet("QLabel#label {\n"
"color:white;}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/icons8-male-user-24 (1).png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.sidebar)
        self.label_2.setGeometry(QtCore.QRect(50, 15, 64, 13))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.S_JPBarang_2 = QtWidgets.QPushButton(self.sidebar)
        self.S_JPBarang_2.setGeometry(QtCore.QRect(18, 50, 152, 30))
        self.S_JPBarang_2.setCheckable(True)
        self.S_JPBarang_2.setAutoExclusive(True)
        self.S_JPBarang_2.setObjectName("S_JPBarang_2")
        self.S_Tempat = QtWidgets.QPushButton(self.sidebar)
        self.S_Tempat.setGeometry(QtCore.QRect(18, 170, 152, 30))
        self.S_Tempat.setCheckable(True)
        self.S_Tempat.setAutoExclusive(True)
        self.S_Tempat.setObjectName("S_Tempat")
        self.S_Voucher = QtWidgets.QPushButton(self.sidebar)
        self.S_Voucher.setGeometry(QtCore.QRect(18, 210, 152, 30))
        self.S_Voucher.setCheckable(True)
        self.S_Voucher.setAutoExclusive(True)
        self.S_Voucher.setObjectName("S_Voucher")
        self.S_Riwayat = QtWidgets.QPushButton(self.sidebar)
        self.S_Riwayat.setGeometry(QtCore.QRect(18, 250, 152, 30))
        self.S_Riwayat.setCheckable(True)
        self.S_Riwayat.setAutoExclusive(True)
        self.S_Riwayat.setObjectName("S_Riwayat")
        self.pushButton_7 = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_7.setGeometry(QtCore.QRect(42, 470, 75, 23))
        self.pushButton_7.setStyleSheet("QPushButton#pushButton_7{\n"
"    border-radius:5px;\n"
"    \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-log-out-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-log-out-24 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setAutoExclusive(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.S_JPMakanan = QtWidgets.QPushButton(self.sidebar)
        self.S_JPMakanan.setGeometry(QtCore.QRect(20, 90, 152, 30))
        self.S_JPMakanan.setCheckable(True)
        self.S_JPMakanan.setAutoExclusive(True)
        self.S_JPMakanan.setObjectName("S_JPMakanan")
        self.S_JPOrang = QtWidgets.QPushButton(self.sidebar)
        self.S_JPOrang.setGeometry(QtCore.QRect(20, 130, 152, 30))
        self.S_JPOrang.setCheckable(True)
        self.S_JPOrang.setAutoExclusive(True)
        self.S_JPOrang.setObjectName("S_JPOrang")
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Tambahkan stylesheet untuk tabel
        table_style = """
        QTableWidget {
            background-color: #f0f8ff; /* Warna latar belakang tabel */
            alternate-background-color: #e6f7ff; /* Warna alternatif baris */
            border: 1px solid #5f9ea0; /* Warna garis luar tabel */
            gridline-color: #87ceeb; /* Warna garis grid */
        }
        QTableWidget::item {
            padding: 5px; /* Padding dalam sel */
            border: none;
        }
        QTableWidget::item:selected {
            background-color: #63b8ff; /* Warna item terpilih */
            color: white; /* Warna teks item terpilih */
        }
        QHeaderView::section {
            background-color: #5f9ea0; /* Warna latar header */
            color: white; /* Warna teks header */
            font-weight: bold; /* Teks tebal */
            border: 1px solid #4682b4; /* Garis pemisah header */
            padding: 4px; /* Padding dalam header */
        }
        QScrollBar:vertical {
            background-color: #f0f8ff;
            width: 10px;
            margin: 0px 3px 0px 3px;
        }
        QScrollBar::handle:vertical {
            background: #5f9ea0;
            min-height: 20px;
            border-radius: 5px;
        }
        QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
            background: none;
            border: none;
        }
        """

        self.viewbarang.setStyleSheet(table_style)
        self.viewmakanan.setStyleSheet(table_style)
        self.vieworang.setStyleSheet(table_style)
        self.viewTempat.setStyleSheet(table_style)
        self.viewvoucher.setStyleSheet(table_style)

        


        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.handle_side_bar_click()
        self.handle_button_clicks_data_tempat()
        self.handle_button_clicks_voucher()
        self.load_data_to_table_view_barang()
        self.load_data_to_table_view_makanan()
        self.load_data_to_table_view_orang()
        self.load_data_to_table_view_tempat()
        self.load_data_to_table_view_voucher()
        self.handle_button_clicks_detail_pengiriman()
        self.handle_button_clicks_riwayat()
        self.pushButton_7.clicked.connect(self.confirm_logout)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Dashboard Admin"))
        self.B_updatebarang.setText(_translate("MainWindow", "Update Data Pengiriman Barang"))
        item = self.viewbarang.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.viewbarang.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pengirim"))
        item = self.viewbarang.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alamat Pengirim"))
        item = self.viewbarang.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nama Penerima"))
        item = self.viewbarang.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Alamat Penerima"))
        item = self.viewbarang.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Nama Barang"))
        item = self.viewbarang.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Berat Barang"))
        item = self.viewbarang.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Jumlah Barang"))
        item = self.viewbarang.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Tgl_Pengiriman"))
        item = self.viewbarang.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Tgl_Penerimaan"))
        item = self.viewbarang.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Status"))
        item = self.viewbarang.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Harga"))
        item = self.viewbarang.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Voucher"))
        item = self.viewbarang.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Status Bayar"))
        item = self.viewmakanan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.viewmakanan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pengirim"))
        item = self.viewmakanan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alamat Pengirim"))
        item = self.viewmakanan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nama Penerima"))
        item = self.viewmakanan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Alamat Penerima"))
        item = self.viewmakanan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Nama Makanan"))
        item = self.viewmakanan.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Jumlah Makanan"))
        item = self.viewmakanan.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Tgl_Pengiriman"))
        item = self.viewmakanan.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Tgl_Penerimaan"))
        item = self.viewmakanan.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Status"))
        item = self.viewmakanan.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Harga"))
        item = self.viewmakanan.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Voucher"))
        item = self.viewmakanan.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Status Bayar"))
        self.B_updatemakanan.setText(_translate("MainWindow", "Update Data Pengiriman Makanan"))
        item = self.vieworang.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.vieworang.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Pemesan"))
        item = self.vieworang.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alamat Pemesan"))
        item = self.vieworang.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Alamat Tujuan"))
        item = self.vieworang.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Kategori"))
        item = self.vieworang.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        item = self.vieworang.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Harga"))
        item = self.vieworang.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Voucher"))
        item = self.vieworang.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Status Bayar"))
        self.B_updateorang.setText(_translate("MainWindow", "Update Data Pengantaran Orang"))
        self.binsertTempat.setText(_translate("MainWindow", "Insert Data Tempat"))
        self.bupdateTempat.setText(_translate("MainWindow", "Update Data Tempat"))
        self.bdeleteTempat.setText(_translate("MainWindow", "Delete Data Tempat"))
        item = self.viewTempat.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.viewTempat.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Alamat"))
        item = self.viewTempat.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Garis Lintang"))
        item = self.viewTempat.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Garis Bujur"))
        self.bupdateVoucer.setText(_translate("MainWindow", "Update Voucer"))
        self.binsertVoucer.setText(_translate("MainWindow", "Insert  Voucer "))
        self.bdeletVoucer.setText(_translate("MainWindow", "Delete Voucer"))
        item = self.viewvoucher.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.viewvoucher.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kode Voucher"))
        item = self.viewvoucher.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Diskon (%)"))
        self.p_makanan_2.setText(_translate("MainWindow", "Data Riwayat Makanan"))
        self.p_orang_2.setText(_translate("MainWindow", "Data Riwayat Orang"))
        self.p_makanan_3.setText(_translate("MainWindow", "Data Riwayat Barang"))
        self.label_2.setText(_translate("MainWindow", "Admin"))
        self.S_JPBarang_2.setText(_translate("MainWindow", "Data Pengiriman Barang"))
        self.S_Tempat.setText(_translate("MainWindow", "Data Tempat"))
        self.S_Voucher.setText(_translate("MainWindow", "Data Voucher"))
        self.S_Riwayat.setText(_translate("MainWindow", "Log Riwayat"))
        self.pushButton_7.setText(_translate("MainWindow", "Log Out"))
        self.S_JPMakanan.setText(_translate("MainWindow", "Data Pengiriman Makanan"))
        self.S_JPOrang.setText(_translate("MainWindow", "Data Antar Orang"))
        
        
    def handle_side_bar_click(self):
        
        self.S_JPBarang_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.sw_pb))  # Data Pengiriman Barang
        self.S_JPMakanan.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.sw_pm))  # Data Pengiriman Makanan
        self.S_JPOrang.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.sw_po))  # Data Antar Orang
        self.S_Tempat.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.DataTempat))  # Data Tempat
        self.S_Voucher.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.DataVoucer))  # Data Voucher
        self.S_Riwayat.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Riwayat))  # Log Riwayat
        
        
    def handle_button_clicks_data_tempat(self):
        self.binsertTempat.clicked.connect(self.openinsertDataTempat)
        self.bupdateTempat.clicked.connect(self.openupdateDataTempat)
        self.bdeleteTempat.clicked.connect(self.opendeleteDataTempat)
        
    def handle_button_clicks_voucher(self):
        self.binsertVoucer.clicked.connect(self.openinsertVoucher)
        self.bupdateVoucer.clicked.connect(self.openupdateVoucher)
        self.bdeletVoucer.clicked.connect(self.opendeleteVoucher)
        
    def handle_button_clicks_detail_pengiriman(self):
        self.B_updatebarang.clicked.connect(self.opendetailpengirimanbarang)
        self.B_updatemakanan.clicked.connect(self.opendetailpengirimanmakanan)
        self.B_updateorang.clicked.connect(self.opendetailantarorang)
    
    def handle_button_clicks_riwayat(self):
        self.p_makanan_2.clicked.connect(self.openriwayatmakanan)
        self.p_orang_2.clicked.connect(self.openriwayatorang)
        self.p_makanan_3.clicked.connect(self.openriwayatbarang)

    def openinsertDataTempat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = InsertTempat()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def openupdateDataTempat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = UpdateTempat()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def opendeleteDataTempat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = DeleteTempat()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    

    def openinsertVoucher(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = InsertVoucher()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def openupdateVoucher(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = UpdateVoucher()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def opendeleteVoucher(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = DeleteVoucher()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
        
    def opendetailpengirimanbarang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = DetailPengirimanBarang()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def opendetailpengirimanmakanan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = DetailPengirimanMakanan()
        self.ui.setupUi(self.window)        
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def opendetailantarorang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = DetailAntarOrang()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    
    def openriwayatbarang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = RB()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    
    def openriwayatmakanan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = RM()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    
    def openriwayatorang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = RO()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    
    
    
    def load_data_to_table_view_barang(self):
        self.viewbarang.setRowCount(0)
        data = PB.load_all_data()
        for row_number, row_data in enumerate(data):
            self.viewbarang.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.viewbarang.setItem(row_number, column_number, item)
                 
    def load_data_to_table_view_makanan(self):
        self.viewmakanan.setRowCount(0)
        data = PM.load_all_data()
        for row_number, row_data in enumerate(data):
            self.viewmakanan.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.viewmakanan.setItem(row_number, column_number, item)
                
    def load_data_to_table_view_orang(self):
        self.vieworang.setRowCount(0)
        data = PO.load_all_data()
        for row_number, row_data in enumerate(data):
            self.vieworang.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.vieworang.setItem(row_number, column_number, item)
                    
    def load_data_to_table_view_voucher(self):
        self.viewvoucher.setRowCount(0)
        data = VC.load_all_data()
        for row_number, row_data in enumerate(data):
            self.viewvoucher.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.viewvoucher.setItem(row_number, column_number, item)
    
                    
    def load_data_to_table_view_tempat(self):
        self.viewTempat.setRowCount(0)
        data = AL.load_all_data()
        for row_number, row_data in enumerate(data):
            self.viewTempat.insertRow(row_number)
            for column_number, data_item in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(data_item))
                self.viewTempat.setItem(row_number, column_number, item)

    def confirm_logout(self):
        from welcome import Ui_Form as wel
        reply = QtWidgets.QMessageBox.question(
            None, "Konfirmasi Logout",
            "Apakah Anda yakin ingin logout?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )
        if reply == QtWidgets.QMessageBox.Yes:
            self.window = QtWidgets.QWidget()
            self.ui = wel()
            self.ui.setupUi(self.window)
            self.window.show()
            QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
