# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_voucher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from voucher import Voucher as VC

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 120, 120, 20))
        self.lineEdit_3.setStyleSheet("QLineEdit#lineEdit_3 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 80, 120, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(-600, -10, 1200, 800))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/pengiriman-barang-satu-hari-sampai.jpg);\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 80, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 180, 100, 23))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(230, 20, 150, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 120, 100, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 180, 100, 23))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9.raise_()
        self.pushButton_2.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_3.clicked.connect(self.openhomeadmin)
        self.pushButton_2.clicked.connect(self.simpan_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Kode Voucher"))
        self.pushButton_2.setText(_translate("MainWindow", "Simpan"))
        self.label_7.setText(_translate("MainWindow", "Insert Voucher"))
        self.label.setText(_translate("MainWindow", "Diskon (%)"))
        self.pushButton_3.setText(_translate("MainWindow", "Kembali"))

    def openhomeadmin(self):        
        import home_admin as ha
        self.window = QtWidgets.QMainWindow()
        self.ui = ha.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
        
    def simpan_data(self):
        kode_voucher = self.lineEdit_2.text()
        diskon_persen = self.lineEdit_3.text()  
        rows_inserted = VC.insert_data(kode_voucher, diskon_persen)
        if rows_inserted is not None and rows_inserted > 0:
                QtWidgets.QMessageBox.information(None, "Berhasil", "Data berhasil disimpan.")
                self.lineEdit_2.clear()
                self.lineEdit_3.clear()
        else:
                QtWidgets.QMessageBox.warning(None, "Gagal", "Data gagal disimpan.")

import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
