# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_data_makanan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from alamat import Alamat
from pengiriman_makanan import PengirimanMakanan as PM

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 110, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 190, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(240, 150, 120, 21))
        self.comboBox_3.setStyleSheet("QComboBox#comboBox_3 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(240, 270, 120, 21))
        self.lineEdit_7.setStyleSheet("QLineEdit#lineEdit_7 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 390, 100, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(240, 110, 120, 21))
        self.lineEdit.setStyleSheet("QLineEdit#lineEdit {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(240, 230, 120, 21))
        self.comboBox_2.setStyleSheet("QComboBox#comboBox_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 20, 210, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 230, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 190, 120, 21))
        self.lineEdit_3.setStyleSheet("QLineEdit#lineEdit_3 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 270, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 80, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 80, 80, 21))
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 80, 35, 21))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 390, 100, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-280, -30, 741, 611))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/533-5338308_food-delivery-png-download-food-delivery-transparent-png.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(90, 310, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(240, 310, 120, 21))
        self.lineEdit_8.setStyleSheet("QLineEdit#lineEdit_8 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_5.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.comboBox_3.raise_()
        self.lineEdit_7.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.comboBox_2.raise_()
        self.label_10.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.lineEdit_3.raise_()
        self.label_9.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_11.raise_()
        self.lineEdit_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.getDataAlamat()
        #aksi button 
        self.pushButton_3.clicked.connect(self.openhomepelanggan)
        self.pushButton.clicked.connect(self.updateData)
        self.pushButton_2.clicked.connect(self.CariData)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nama Pengirim"))
        self.label_7.setText(_translate("MainWindow", "Nama Penerima"))
        self.pushButton.setText(_translate("MainWindow", "Update"))
        self.label_10.setText(_translate("MainWindow", "Update Data Makanan"))
        self.label_2.setText(_translate("MainWindow", "Alamat Pengirim"))
        self.label_8.setText(_translate("MainWindow", "Alamat Penerima"))
        self.label_9.setText(_translate("MainWindow", "Nama Makanan"))
        self.label_3.setText(_translate("MainWindow", "ID"))
        self.pushButton_2.setText(_translate("MainWindow", "Cari"))
        self.pushButton_3.setText(_translate("MainWindow", "Kembali"))
        self.label_11.setText(_translate("MainWindow", "Jumlah Makanan"))
        
    def openhomepelanggan(self):
        import home_pelanggan as hp
        self.window = QtWidgets.QMainWindow()
        self.ui = hp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def getDataAlamat(self):
        data = Alamat.select_data()
        self.comboBox_3.addItems(data)
        self.comboBox_2.addItems(data)  
        
    def CariData(self):
        id = self.lineEdit_2.text()  
        data = PM.select_data_by_id(id)  
        if data:
            self.lineEdit.setText(data[0][1]) 
            self.comboBox_2.setCurrentText(data[0][2])  
            self.lineEdit_3.setText(data[0][3]) 
            self.comboBox_3.setCurrentText(data[0][4])  
            self.lineEdit_7.setText(data[0][5])  
            self.lineEdit_8.setText(str(data[0][6])) 
            
        else:
            QtWidgets.QMessageBox.warning(
                None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!"
            )
        
    def updateData(self):
        id = self.lineEdit_2.text()  # ID dari LineEdit
        nama_pengirim = self.lineEdit.text()  # Nama Pengirim
        alamat_pengirim = self.comboBox_3.currentText()  # Alamat Pengirim (ComboBox)
        nama_penerima = self.lineEdit_3.text()  # Nama Penerima
        alamat_penerima = self.comboBox_2.currentText()  # Alamat Penerima (ComboBox)
        nama_makanan = self.lineEdit_7.text()  # Nama Makanan
        jumlah_makanan = self.lineEdit_8.text()  # Jumlah Makanan
        
        rows_inserted =  PM.update_data(id, nama_pengirim, alamat_pengirim, nama_penerima, alamat_penerima, nama_makanan,jumlah_makanan)
        if rows_inserted is not None and rows_inserted > 0:
                QtWidgets.QMessageBox.information(None, "Berhasil", "Data berhasil diperbarui.")
                self.lineEdit.clear()
                self.lineEdit_3.clear()
                self.lineEdit_7.clear()
                self.lineEdit_8.clear()
                self.comboBox_3.setCurrentIndex(0)
                self.comboBox_2.setCurrentIndex(0)        
        else:
                QtWidgets.QMessageBox.warning(None, "Gagal", "Data gagal diperbarui.")
        
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
