# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_data_pengiriman_makanan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pengiriman_makanan import PengirimanMakanan as PM

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(310, 550, 120, 20))
        self.label_26.setStyleSheet("QLabel#label_26 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 80, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 270, 90, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 110, 90, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(160, 510, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 80, 40, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 190, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(160, 430, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 610, 100, 23))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 150, 120, 20))
        self.label_11.setStyleSheet("QLabel#label_11 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(310, 190, 120, 20))
        self.label_14.setStyleSheet("QLabel#label_14 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 20, 325, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(310, 270, 120, 20))
        self.label_16.setStyleSheet("QLabel#label_16 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 600, 800))
        self.label_9.setStyleSheet("\n"
"background-image: url(:/newPrefix/533-5338308_food-delivery-png-download-food-delivery-transparent-png.png);\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(160, 350, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(160, 310, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(160, 390, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(310, 310, 120, 20))
        self.label_18.setStyleSheet("QLabel#label_18 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(160, 470, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(310, 510, 120, 20))
        self.label_25.setStyleSheet("QLabel#label_25 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(310, 470, 120, 20))
        self.label_24.setStyleSheet("QLabel#label_24\n"
" {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 80, 71, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 110, 120, 20))
        self.label_10.setStyleSheet("QLabel#label_10 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 150, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 390, 120, 20))
        self.lineEdit_4.setStyleSheet("QLineEdit#lineEdit_4 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 230, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 430, 120, 22))
        self.comboBox.setStyleSheet("QComboBox#comboBox {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["Dikemas", "Dikirim", "Selesai"]) 
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(310, 230, 120, 20))
        self.label_15.setStyleSheet("QLabel#label_15 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(160, 550, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 610, 100, 23))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 350, 120, 20))
        self.lineEdit_3.setStyleSheet("QLineEdit#lineEdit_3 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9.raise_()
        self.label_26.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_19.raise_()
        self.pushButton_3.raise_()
        self.label_3.raise_()
        self.label_23.raise_()
        self.pushButton_4.raise_()
        self.label_11.raise_()
        self.label_14.raise_()
        self.label_7.raise_()
        self.label_16.raise_()
        self.label_21.raise_()
        self.label_12.raise_()
        self.label_22.raise_()
        self.label_18.raise_()
        self.label_13.raise_()
        self.label_25.raise_()
        self.label_24.raise_()
        self.lineEdit_2.raise_()
        self.label_10.raise_()
        self.label_2.raise_()
        self.lineEdit_4.raise_()
        self.label_4.raise_()
        self.comboBox.raise_()
        self.label_15.raise_()
        self.label_20.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton_4.clicked.connect(self.openhomeadmin)
        self.pushButton_3.clicked.connect(self.CariData)
        self.pushButton_2.clicked.connect(self.updateData)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "ID"))
        self.label_5.setText(_translate("MainWindow", "Nama Makanan"))
        self.label.setText(_translate("MainWindow", "Nama Pengirim"))
        self.label_19.setText(_translate("MainWindow", "Voucher"))
        self.pushButton_3.setText(_translate("MainWindow", "Cari"))
        self.label_3.setText(_translate("MainWindow", "Nama Penerima"))
        self.label_23.setText(_translate("MainWindow", "Status"))
        self.pushButton_4.setText(_translate("MainWindow", "Kembali"))
        self.label_7.setText(_translate("MainWindow", "Update Data Pengiriman Makanan"))
        self.label_21.setText(_translate("MainWindow", "Tgl Pengiriman"))
        self.label_12.setText(_translate("MainWindow", "Jumlah Makanan"))
        self.label_22.setText(_translate("MainWindow", "Tgl Penerimaan"))
        self.label_13.setText(_translate("MainWindow", "Harga"))
        self.label_2.setText(_translate("MainWindow", "Alamat Pengirim"))
        self.label_4.setText(_translate("MainWindow", "Alamat Penerima"))
        self.label_20.setText(_translate("MainWindow", "Status Pembayaran"))
        self.pushButton_2.setText(_translate("MainWindow", "Update"))
        
    def openhomeadmin(self):        
        import home_admin as ha
        self.window = QtWidgets.QMainWindow()
        self.ui = ha.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
    def CariData(self):
        id = self.lineEdit_2.text()
        data = PM.select_data_by_id(id)
        if data:
            self.label_10.setText(data[0][1])  # Nama Pengirim
            self.label_11.setText(data[0][2])  # Alamat Pengirim
            self.label_14.setText(data[0][3])  # Nama Penerima
            self.label_15.setText(data[0][4])  # Alamat Penerima
            self.label_16.setText(data[0][5])  # Nama Barang
            self.label_18.setText(str(data[0][6]))  # Jumlah Barang
            self.comboBox.setCurrentText(data[0][9])
            self.label_24.setText(str(data[0][10]))  # Harga
            self.label_25.setText(data[0][11])  # Voucher
            self.label_26.setText(data[0][12])  # Status Pembayaran
        else:
            QtWidgets.QMessageBox.warning(
                None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!"
            )
    def updateData(self):
        id = self.lineEdit_2.text()
        nama_pengirim = self.label_10.text() 
        alamat_pengirim = self.label_11.text()
        nama_penerima = self.label_14.text()
        alamat_penerima = self.label_15.text()
        nama_makanan = self.label_16.text()
        jumlah_makanan = self.label_18.text()
        tgl_pengiriman = self.lineEdit_3.text()
        tgl_penerimaan = self.lineEdit_4.text()
        status = self.comboBox.currentText()
        harga = self.label_24.text()
        voucher = self.label_25.text()
        status_pembayaran = self.label_26.text()
        if status == "Belum Dibayar":
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Data belum dibayar dan tidak dapat diperbarui.")
                return

        # Validasi tanggal pengiriman
        if not self.validate_date(tgl_pengiriman,tgl_pengiriman):
                QtWidgets.QMessageBox.warning(None, "Peringatan", "Tanggal pengiriman tidak valid! Gunakan format YYYY-MM-DD.")
                return

        rows_updated = PM.update_detail_pengiriman_makanan(
            id, nama_pengirim, alamat_pengirim, nama_penerima,
            alamat_penerima, nama_makanan, jumlah_makanan, tgl_pengiriman, tgl_penerimaan, status, harga, voucher, status_pembayaran
        )

        if rows_updated is not None and rows_updated > 0:
                QtWidgets.QMessageBox.information(None, "Berhasil", "Data berhasil diperbarui.")
                self.lineEdit_3.clear()
                self.lineEdit_4.clear()
                self.label_10.clear()
                self.label_11.clear()
                self.label_14.clear()
                self.label_15.clear()
                self.label_16.clear()
               
                self.label_18.clear()
                self.label_24.clear()
                self.label_25.clear()
                self.label_26.clear()
        else:
            QtWidgets.QMessageBox.warning(None, "Gagal", "Data gagal diperbarui.")
            

    def validate_date(self, *dates):
        import re
        from datetime import datetime
        pattern = r"^\d{4}-\d{2}-\d{2}$"
        for date_str in dates:
                if not re.match(pattern, date_str):
                        return False
                try:
                        datetime.strptime(date_str, "%Y-%m-%d")
                except ValueError:
                        return False
        return True

import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
