# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_voucher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from voucher import Voucher as VC

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(-590, -10, 1200, 800))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/pengiriman-barang-satu-hari-sampai.jpg);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 70, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 200, 100, 23))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 150, 120, 20))
        self.label_11.setStyleSheet("QLineEdit#label_11 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 110, 120, 20))
        self.label_10.setStyleSheet("QLineEdit#label_10 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 10, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 70, 40, 20))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 110, 100, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 70, 71, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 200, 100, 23))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 150, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton_4.clicked.connect(self.openhomeadmin)
        self.pushButton_3.clicked.connect(self.CariData)
        self.pushButton_2.clicked.connect(self.updateData)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "ID"))
        self.pushButton_4.setText(_translate("MainWindow", "Kembali"))
        self.label_7.setText(_translate("MainWindow", "Update Voucher"))
        self.pushButton_3.setText(_translate("MainWindow", "Cari"))
        self.label.setText(_translate("MainWindow", "Kode Voucher"))
        self.pushButton_2.setText(_translate("MainWindow", "Update"))
        self.label_2.setText(_translate("MainWindow", "Diskon (%)"))
        
    def openhomeadmin(self):        
        import home_admin as ha
        self.window = QtWidgets.QMainWindow()
        self.ui = ha.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def CariData(self):
        id = self.lineEdit_2.text()  
        data = VC.select_data_by_id(id)  
        if data:
            self.label_10.setText(data[0][1]) 
            self.label_11.setText(str(data[0][2]))
        else:
            QtWidgets.QMessageBox.warning(
                None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!"
            )
    def updateData(self):
        id = self.lineEdit_2.text()  # ID dari LineEdit
        kode_voucher = self.label_10.text() 
        diskon_persen = self.label_11.text()
        rows_inserted = VC.update_data(id,kode_voucher, diskon_persen)
        if rows_inserted is not None and rows_inserted > 0:
                QtWidgets.QMessageBox.information(None, "Berhasil", "Data berhasil diperbarui.")
                self.label_10.clear()
                self.label_11.clear()
                       
        else:
                QtWidgets.QMessageBox.warning(None, "Gagal", "Data gagal diperbarui.")
        
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
