# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_data_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pengiriman_barang import PengirimanBarang as PB
from alamat import Alamat

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 534)
        MainWindow.setStyleSheet("QWidget: url(:/newPrefix/pengiriman-barang-satu-hari-sampai.jpg)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 230, 120, 22))
        self.comboBox_2.setStyleSheet("QComboBox#comboBox_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 110, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 270, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(230, 150, 120, 20))
        self.comboBox.setStyleSheet("QComboBox#comboBox {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 310, 120, 20))
        self.lineEdit_6.setStyleSheet("QLineEdit#lineEdit_6 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 110, 120, 20))
        self.lineEdit.setStyleSheet("QLineEdit#lineEdit {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(125, 20, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 190, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 190, 120, 20))
        self.lineEdit_3.setStyleSheet("QLineEdit#lineEdit_3 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 270, 120, 20))
        self.lineEdit_5.setStyleSheet("QLineEdit#lineEdit_5 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 420, 100, 23))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 310, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 80, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 80, 71, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 80, 40, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 420, 100, 23))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(-470, 0, 951, 1201))
        self.label_9.setStyleSheet("\n"
"background-image: url(:/newPrefix/ekspedisi-adalah.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 350, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(230, 350, 120, 20))
        self.lineEdit_9.setStyleSheet("QLineEdit#lineEdit_9 {\n"
"    border: 1px solid black; /* Border hitam dengan ketebalan 2px */\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 431, 481))
        self.label_13.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 0), stop:0.375 rgba(0, 0, 0, 25),stop:0.835227 rgba(0,0,0,15));")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_13.raise_()
        self.label_9.raise_()
        self.comboBox_2.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.comboBox.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit.raise_()
        self.label_7.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()
        self.label_2.raise_()
        self.lineEdit_5.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_12.raise_()
        self.lineEdit_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.getDataAlamat()
        #aksi button 
        self.pushButton_4.clicked.connect(self.openhomepelanggan)
        self.pushButton_2.clicked.connect(self.updateData)
        self.pushButton_3.clicked.connect(self.CariData)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nama Pengirim"))
        self.label_5.setText(_translate("MainWindow", "Nama Barang"))
        self.label_4.setText(_translate("MainWindow", "Alamat Penerima"))
        self.label_7.setText(_translate("MainWindow", "Update Data Barang"))
        self.label_3.setText(_translate("MainWindow", "Nama Penerima"))
        self.label_2.setText(_translate("MainWindow", "Alamat Pengirim"))
        self.pushButton_2.setText(_translate("MainWindow", "Update"))
        self.label_6.setText(_translate("MainWindow", "Berat Barang"))
        self.label_8.setText(_translate("MainWindow", "ID"))
        self.pushButton_3.setText(_translate("MainWindow", "Cari"))
        self.pushButton_4.setText(_translate("MainWindow", "Kembali"))
        self.label_12.setText(_translate("MainWindow", "Jumlah Barang"))

    def openhomepelanggan(self):
        import home_pelanggan as hp
        self.window = QtWidgets.QMainWindow()
        self.ui = hp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
        
    def getDataAlamat(self):
        data = Alamat.select_data()
        self.comboBox.addItems(data)
        self.comboBox_2.addItems(data)  
        
    def CariData(self):
        id = self.lineEdit_2.text()  
        data = PB.select_data_by_id(id)  
        if data:
            self.lineEdit.setText(data[0][1]) 
            self.comboBox.setCurrentText(data[0][2])  
            self.lineEdit_3.setText(data[0][3]) 
            self.comboBox_2.setCurrentText(data[0][4])  
            self.lineEdit_5.setText(data[0][5])  
            self.lineEdit_6.setText(str(data[0][6])) 
            self.lineEdit_9.setText(str(data[0][7]))
        else:
            QtWidgets.QMessageBox.warning(
                None, "Peringatan", "Data dengan ID tersebut tidak ditemukan!"
            )

    def updateData(self):
        id= self.lineEdit_2.text()  
        nama_pengirim = self.lineEdit.text()  
        alamat_pengirim = self.comboBox.currentText()  
        nama_penerima = self.lineEdit_3.text()  
        alamat_penerima = self.comboBox_2.currentText() 
        nama_barang = self.lineEdit_5.text() 
        berat_barang = self.lineEdit_6.text() 
        jumlah_barang = self.lineEdit_9.text()
        rows_inserted =  PB.update_data(id, nama_pengirim, alamat_pengirim, nama_penerima, alamat_penerima, nama_barang,berat_barang,jumlah_barang)
        if rows_inserted is not None and rows_inserted > 0:
                QtWidgets.QMessageBox.information(None, "Berhasil", "Data berhasil diperbarui.")
                self.lineEdit.clear()
                self.lineEdit_3.clear()
                self.lineEdit_5.clear()
                self.lineEdit_6.clear()
                self.lineEdit_9.clear()
                self.comboBox.setCurrentIndex(0)
                self.comboBox_2.setCurrentIndex(0)
        else:
                QtWidgets.QMessageBox.warning(None, "Gagal", "Data gagal diperbarui.")
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
