# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from registrasi import Ui_Form as RegistrasiForm 
from login import Ui_Form as LoginForm 
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 550)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 40, 390, 500))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 370, 500))
        self.label.setStyleSheet("border-image: url(:/images/drops-5451924_1280.jpg);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 370, 500))
        self.label_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50),stop:0.835227 rgba(0,0,0,75));\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(85, 40, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgba(255,255,255,210);")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(95, 260, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
"        stop:0 rgba(78, 47, 20, 219), stop:1 rgba(100, 60, 30, 226)); /* Cokelat gelap */\n"
"    color: rgba(255, 255, 255, 210); /* Warna teks putih */\n"
"    border-radius: 5px; /* Sudut melengkung */\n"
"}\n"
"\n"
"QPushButton#pushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
"        stop:0 rgba(100, 60, 30, 219), stop:1 rgba(120, 70, 40, 226)); /* Cokelat sedikit lebih terang */\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(60, 40, 20, 200); /* Cokelat sangat gelap (hampir hitam) */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(40, 80, 310, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255,255,255,210);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(98, 180, 194, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255,255,255,210);")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 155, 310, 291))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(120, 200, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgba(255,255,255,210);")
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(95, 330, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
"        stop:0 rgba(78, 47, 20, 219), stop:1 rgba(100, 60, 30, 226)); /* Cokelat gelap */\n"
"    color: rgba(255, 255, 255, 210); /* Warna teks putih */\n"
"    border-radius: 5px; /* Sudut melengkung */\n"
"}\n"
"\n"
"QPushButton#pushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
"        stop:0 rgba(100, 60, 30, 219), stop:1 rgba(120, 70, 40, 226)); /* Cokelat sedikit lebih terang */\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(60, 40, 20, 200); /* Cokelat sangat gelap (hampir hitam) */\n"
"}\n"
"\n"
"QPushButton#pushButton_2 {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
"        stop:0 rgba(78, 47, 20, 219), stop:1 rgba(100, 60, 30, 226)); /* Cokelat gelap */\n"
"    color: rgba(255, 255, 255, 210); /* Warna teks putih */\n"
"    border-radius: 5px; /* Sudut melengkung */\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, \n"
"        stop:0 rgba(100, 60, 30, 219), stop:1 rgba(120, 70, 40, 226)); /* Cokelat sedikit lebih terang */\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(60, 40, 20, 200); /* Cokelat sangat gelap (hampir hitam) */\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.pushButton_2.raise_()
        
        #registrasi 
        self.pushButton_2.clicked.connect(self.open_register_form)
        #login 
        self.pushButton.clicked.connect(self.open_login_form)
  
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Selamat Datang"))
        self.pushButton.setText(_translate("Form", "L o g In"))
        self.label_5.setText(_translate("Form", "Di Sistem Pengiriman Barang"))
        self.label_6.setText(_translate("Form", "Silahkan Login / Registrasi"))
        self.label_7.setText(_translate("Form", " untuk melanjutkan"))
        self.pushButton_2.setText(_translate("Form", "R e g i s t e r"))
        
    def open_register_form(self):
        self.window = QtWidgets.QWidget()
        self.ui = RegistrasiForm()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())

    def open_login_form(self):
        self.window = QtWidgets.QWidget()
        self.ui = LoginForm()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QWidget.close(QtWidgets.QApplication.activeWindow())
import res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
